<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <script>
        // 正常情况
        let p1 = new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve('hello');
            }, 2000);
        });
        let p2 = new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve('world');
            }, 100);
        });
        let p3 = new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve('aaaaa');
            }, 5000);
        });
        let p = Promise.all([p1, p2, p3]).then((res) => {
            // 按 p1,p2,p3 的顺序返回
            console.log(res.join(' '));             // hello world aaaaa
        });

        // 异常情况
        let ep1 = new Promise((resolve, reject) => {
            setTimeout(() => {
                throw new Error('error1');
            }, 2000);
        });
        let ep2 = new Promise((resolve, reject) => {
            setTimeout(() => {
                throw new Error('error2');
            }, 5000);
        });
        let ep3 = new Promise((resolve, reject) => {
            setTimeout(() => {
                throw new Error('error3');
            }, 1000);
        });
        let ep = Promise.all([ep1, ep2, ep3]).then(res => {
            console.log(res.join(' '));
        })
        .catch(err => {
            // 按时间依次输出报错
            console.log(err);
        });

        // 部分报错情况
        let p4 = new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve('resolve');
            }, 2000);
        });
        let ep5 = new Promise((resolve, reject) => {
            setTimeout(() => {
                reject(new Error('async error'));
            }, 1000);
        });
        let ep6 = new Promise((resolve, reject) => {
            setTimeout(() => {
                reject('reject');
            }, 3000);
        });
        let p7 = new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve('first resolve');
            }, 0);
        });
        let ep8 = new Promise((resolve, reject) => {
            setTimeout(() => {
                reject('first reject');
            }, 0);
        });
        // 有报错不执行then
        let mix = Promise.all([p4, ep5, ep6, p7, ep8]).then(res => {
            console.log(res);
        })
        .catch(err => {
            // 只输出第一个错误(reject('first reject')),后面的不再执行
            console.error(err);
        });

        // 捕获自身的错误
        let p9 = new Promise((resolve, reject) => {
            resolve('p9 ok');
        });
        let ep10 = new Promise((resolve, reject) => {
            reject('ep10 failed');
        })
        .catch(err => {
            // 捕获自身的 reject,处理完后自身状态也会变成 resolved
            console.log('error caught:' + err);
        });
        let p11 = new Promise((resolve, reject) => {
            resolve('p11 ok');
        });
        // 由于 ep10处理了自身 reject,状态变成 resolved,所以所有 Promise 状态都变为 resolved,最终进入 then,但 ep10 没有数据返回
        let catchSelf = Promise.all([p9, ep10, p11]).then(res => {
            // 输出 p9 ok p11 ok
            console.log(res.join(' '));
        })
        .catch(err => {
            console.log('error:' + err);
        });
    </script>
</body>
</html>